### ISSUE TITLE
Unbreakable

### ISSUE THREAD

**Issue by RuneKeeper666** [TheidenHD/Psi#2]
# Version Information
Forge version: forge-1.20.1-47.1.106
Psi version: Psi-1.20-103.jar (alpha 5)

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. load world
2. attempt to break block normally breakable with a diamond pick axe with a diamond pick (obsidian, ancient debree, etc (includes modded blocks))

What I expected to happen: Block breaks in a timely fashion dropping an item

What happened instead: Block is destroyed (not drops item and is kind of slow) unless broken with a netherite pick axe

**Comment by TheidenHD** [comment]
https://github.com/TheidenHD/Psi/releases/tag/1.20-Alpha-6

**Comment by TheidenHD** [comment]
https://github.com/TheidenHD/Psi/releases/tag/1.20-Alpha-6
